[project]
name = "my-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=6.0.0",
    "google-genai>=2.13.0",
    "pyautogui>=0.9.54",
    "pynput>=1.8.2",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.2.2",
]
